### ISSUE TITLE
flag_fillr_ error messages

### ISSUE THREAD

**Issue by taehyun-lim** [RobertMyles/flagfillr#4]
Hi, 

I tried flag_fillr_states("United States of America”) and it says "Error in ~!is.na(partner) : object 'partner' not found"

I also tried your Brazil example, but it says: 
Combining flags and data...

Creating plot...
Error: stat_sf requires the following missing aesthetics: geometry

**Comment by RobertMyles** [comment]
Hi, thanks for the issue. I've been meaning to get back to this package  (it's a bit of a WIP) and fix up a few things. Should be able to get to the bottom of these errors over the next week or so.

**Comment by RobertMyles** [comment]
Not actively developing this package anymore.
