### ISSUE TITLE
Dependency (rnaturalearthhires) not available for R >= 4.2

### ISSUE THREAD

**Issue by MartinSchweinberger** [RobertMyles/flagfillr#6]
ERROR: dependency 'rnaturalearthhires' is not available for package 'flagfillr'
* removing 'MY PATH TO LIBRARY

**Comment by RobertMyles** [comment]
Hi Martin,
This package is not on CRAN so you need to install it using the remotes package or devtools, as mentioned here:  https://github.com/ropensci/rnaturalearth
